### ISSUE TITLE
footsteps.pk3 alters behavior of mods that are loaded after it

### ISSUE THREAD

**Issue by mmaulwurff** [DaZombieKiller/zk-resources#2]
Hello!

I was writing a mod, completely unrelated to footsteps, and noticed that it was not working if loaded after footsteps.pk3 (I have pk3 from releases in this repository). It seems that ENTER ACS script in my mod just was not called. It happens only if my mod is loaded after footsteps.pk3.

I tried to make a minimal mod to represent this bug. See helloworld.zip: it contains only one script:
`script "Helloworld" ENTER
{
	print(s:"Hello, world!");
}`
- if loaded without any other mods, it just prints "Hello, world!" on the center of the screen on level start.
- if loaded before footsteps.pk3, it prints the same.
- BUT if loaded after footsteps.pk3, it prints "step_flats". Very strange.
Though it is not an original problem, I think this wrong string printing maybe somehow connected to not running ENTER scripts. The common problem is that footsteps.pk3 somehow alters behavior of scripts that are loaded after.

I don't have much experience in ACS, and your mod is even not ACS, so I don't what I can do with this problem myself, and to resolve this problem I need help. I thought that scripts in different mods were isolated from each other. I don't know if this a bug in GZDoom (version 3.2.5) or in footsteps.pk3, or I am doing something wrong myself.

[helloworld.zip](https://github.com/DaZombieKiller/zk-resources/files/1733364/helloworld.zip)

P.S. Thank you for footsteps mod! I am enjoying it very much, it brings immersion and atmosphere to the game.

**Comment by mmaulwurff** [comment]
The issue is solved by turning ACS script into a library with
`#library "LIBMYMOD"`.
Why did this help, I don't know. Maybe it is one of ACS quirks, or I just need to understand it better.
Sorry for bothering.

**Comment by DaZombieKiller** [comment]
No worries! Glad you managed to solve it since I didn't have time to look at this earlier.
The problem is that when you use the ACC compiler, the string tables get all messed up if you don't use the #library directive, so you see random strings get used.

You can also fix this by using the superior gdcc-acc ACS compiler, which gives you additional features as well as fixing various issues with the language.
